/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveExpense"
      | "contractor"
      | "fundProject"
      | "getAllExpenses"
      | "getApprovedExpenses"
      | "getRejectedExpenses"
      | "projectFunds"
      | "projectTotalBudget"
      | "proposeExpense"
      | "rejectExpense"
      | "roleRegistry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveExpense",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundProject",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllExpenses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovedExpenses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRejectedExpenses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectTotalBudget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeExpense",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectExpense",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "approveExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contractor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllExpenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovedExpenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRejectedExpenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectTotalBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleRegistry",
    data: BytesLike
  ): Result;
}

export interface Project extends BaseContract {
  connect(runner?: ContractRunner | null): Project;
  waitForDeployment(): Promise<this>;

  interface: ProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveExpense: TypedContractMethod<
    [_expense: AddressLike],
    [void],
    "nonpayable"
  >;

  contractor: TypedContractMethod<[], [string], "view">;

  fundProject: TypedContractMethod<[], [void], "payable">;

  getAllExpenses: TypedContractMethod<[], [string[]], "view">;

  getApprovedExpenses: TypedContractMethod<[], [string[]], "view">;

  getRejectedExpenses: TypedContractMethod<[], [string[]], "view">;

  projectFunds: TypedContractMethod<[], [string], "view">;

  projectTotalBudget: TypedContractMethod<[], [bigint], "view">;

  proposeExpense: TypedContractMethod<
    [_amount: BigNumberish, _description: string],
    [void],
    "nonpayable"
  >;

  rejectExpense: TypedContractMethod<
    [_expense: AddressLike],
    [void],
    "nonpayable"
  >;

  roleRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveExpense"
  ): TypedContractMethod<[_expense: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contractor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundProject"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getAllExpenses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getApprovedExpenses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRejectedExpenses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "projectFunds"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectTotalBudget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeExpense"
  ): TypedContractMethod<
    [_amount: BigNumberish, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectExpense"
  ): TypedContractMethod<[_expense: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roleRegistry"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
