/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProjectFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "getAllProjects" | "proposeProject" | "roleRegistry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllProjects",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleRegistry",
    data: BytesLike
  ): Result;
}

export interface ProjectFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectFactory;
  waitForDeployment(): Promise<this>;

  interface: ProjectFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllProjects: TypedContractMethod<[], [string[]], "view">;

  proposeProject: TypedContractMethod<
    [_contractor: AddressLike],
    [void],
    "nonpayable"
  >;

  roleRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllProjects"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "proposeProject"
  ): TypedContractMethod<[_contractor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roleRegistry"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
