/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProjectFundsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contractor"
      | "deposit"
      | "expenseBalances"
      | "expenseWithdrawn"
      | "projectContract"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "contractor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expenseBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expenseWithdrawn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "contractor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expenseBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expenseWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface ProjectFunds extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectFunds;
  waitForDeployment(): Promise<this>;

  interface: ProjectFundsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contractor: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [_expense: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;

  expenseBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  expenseWithdrawn: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  projectContract: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[_expense: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contractor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [_expense: AddressLike, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "expenseBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "expenseWithdrawn"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "projectContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_expense: AddressLike], [void], "nonpayable">;

  filters: {};
}
