/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RoleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "isContractor"
      | "isGovernmentOfficial"
      | "registerContractor"
      | "registerOfficial"
      | "revokeContractor"
      | "revokeOfficial"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isContractor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGovernmentOfficial",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContractor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOfficial",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeContractor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOfficial",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isContractor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGovernmentOfficial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContractor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOfficial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeContractor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOfficial",
    data: BytesLike
  ): Result;
}

export interface RoleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RoleRegistry;
  waitForDeployment(): Promise<this>;

  interface: RoleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  isContractor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isGovernmentOfficial: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  registerContractor: TypedContractMethod<
    [_contractor: AddressLike],
    [void],
    "nonpayable"
  >;

  registerOfficial: TypedContractMethod<
    [_official: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeContractor: TypedContractMethod<
    [_contractor: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeOfficial: TypedContractMethod<
    [_official: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isContractor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isGovernmentOfficial"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerContractor"
  ): TypedContractMethod<[_contractor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerOfficial"
  ): TypedContractMethod<[_official: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeContractor"
  ): TypedContractMethod<[_contractor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeOfficial"
  ): TypedContractMethod<[_official: AddressLike], [void], "nonpayable">;

  filters: {};
}
